name: Python CI
on:
    push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Chekcout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run hello.py
        run: python hello.py
